import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

import './globals.css'
import { TooltipProvider } from '@/src/components/ui/tooltip'
import { cn } from '@/src/lib'

const nunito = Nunito({
	subsets: ['cyrillic'],
	variable: '--font-nunito',
	weight: ['500', '600', '700', '900']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={cn(nunito.variable, 'antialiased')}>
				<TooltipProvider>{children}</TooltipProvider>
			</body>
		</html>
	)
}
